name: Build and Push Docker Image

on: 
    push:
        branches: 
          - main
    pull_request:
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Extract Docker image metadata
              id: meta
              uses: docker/metadata-actions@v5
              with:
                images: ${{ vars.DOCKER_USERNAME}}/my-image